apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-service
  name: grpc-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-service
  template:
    metadata:
      labels:
        app: grpc-service
    spec:
      containers:
        - image: gcr.io/agile-falcon-327511/hello-java:v1
          imagePullPolicy: Always
          name: grpc-service
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 6565
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: normal-port
    - port: 6565
      protocol: TCP
      targetPort: 6565
      name: grpc-port
  selector:
    run: grpc-service
  sessionAffinity: None
  type: NodePort